[package]
name = "simplefs-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
simplefs = { path = "../simplefs" }
anyhow = "1.0"
bytes = { git = "https://github.com/rblaze/embedded-bytes.git" }
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
quickcheck = "1.0"
