[package]
name = "event_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1.1"
fugit = "0.3.6"
intrusive-collections = "0.9.4"

[dev-dependencies]
critical-section = { version = "1.1.1", features = ["std"] }
