[package]
name = "event_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1"
intrusive-collections = { version = "0.9", default-features = false }

[dev-dependencies]
critical-section = { version = "1.1", features = ["std"] }
